import {
  Entity,
  Medicine,
  SaleInvoice,
  FinancialTransaction,
  Expense,
  AppSettings,
  LicenseInfo,
} from '../types';

/**
 * بيانات الترخيص الافتراضية
 */
export const defaultLicense: LicenseInfo = {
  isActivated: true,
  licenseKey: 'PHARMA-PRO-MALIK-2026-9981',
  planType: 'annual',
  startDate: '2026-10-01',
  expiryDate: '2027-10-01',
  pharmacyName: 'صيدلية النور النموذجية',
  clientName: 'د. مالك حريبات',
  clientPhone: '0594345464',
  notes: 'نسخة مرخصة ومعتمدة للصيدلية بواسطة المهندس مالك حريبات',
  activatedBy: 'المهندس مالك حريبات',
};

/**
 * الإعدادات الأولية للنظام - خالية من أي كلمات مرور أو رموز PIN افتراضية صريحة
 * سيتم تعيينها بشكل آمن ومشفر من قبل المدير في شاشة الإعداد الأولى
 */
export const defaultSettings: AppSettings = {
  pharmacyName: 'صيدلية النور النموذجية',
  ownerName: 'د. مالك حريبات',
  phone: '0594345464',
  address: 'الشارع الرئيسي - وسط المدينة',
  currency: '₪',
  taxRate: 0,
  pincode: '', // تم حذف 1234
  superAdminPin: '', // تم حذف 7777
  pincodeHash: '',
  pincodeSalt: '',
  adminUsername: '',
  adminPasswordHash: '',
  adminPasswordSalt: '',
  superAdminPinHash: '',
  superAdminPinSalt: '',
  isPinRequired: true,
  isSetupCompleted: false, // يتطلب إعداد أمني أولي عند أول تشغيل
  sessionTimeoutMinutes: 20, // مهلة انتهاء الجلسة بعد الخمول
  designerName: 'المهندس مالك حريبات',
  designerPhone: '0594345464',
  designerEmail: 'hraibat.malek@gmail.com',
  license: defaultLicense,
};

export const initialEntities: Entity[] = [
  {
    id: 'ent-1',
    name: 'صيدلية الأمل المركزية',
    type: 'pharmacy',
    phone: '0599112233',
    address: 'دورا - الشارع العام',
    currentBalance: 1450.0,
    creditLimit: 5000.0,
    notes: 'تعامل دوري - طلبات تبادل أدوية شهرية',
    createdAt: '2026-08-10',
  },
  {
    id: 'ent-2',
    name: 'صيدلية الشفاء الحديثة',
    type: 'pharmacy',
    phone: '0598774411',
    address: 'الخليل - عين سارة',
    currentBalance: 820.0,
    creditLimit: 3000.0,
    notes: 'صيدلية زميلة لتوفير النواقص',
    createdAt: '2026-08-15',
  },
  {
    id: 'ent-3',
    name: 'شركة بيرزيت للصناعات الدوائية',
    type: 'company',
    phone: '022987654',
    address: 'رام الله - المنطقة الصناعية',
    currentBalance: -4300.0,
    creditLimit: 15000.0,
    notes: 'مورد رئيسي للأدوية العامة والمضادات',
    createdAt: '2026-07-01',
  },
  {
    id: 'ent-4',
    name: 'مستودع أدوية القدس المركزي',
    type: 'supplier',
    phone: '0592334455',
    address: 'بيت لحم - شارع المهد',
    currentBalance: -2150.0,
    creditLimit: 10000.0,
    notes: 'توريد أدوية مستوردة وحليب أطفال ومستلزمات',
    createdAt: '2026-07-20',
  },
  {
    id: 'ent-5',
    name: 'شركة دار الشفاء لصناعة الأدوية',
    type: 'company',
    phone: '0595667788',
    address: 'نابلس - رفيديا',
    currentBalance: -1200.0,
    creditLimit: 8000.0,
    notes: 'وكيل أدوية الضغط والسكري',
    createdAt: '2026-08-01',
  },
  {
    id: 'ent-6',
    name: 'أحمد محمود العواودة (زبون دائم)',
    type: 'customer',
    phone: '0599332211',
    address: 'دورا - حي الصرفة',
    currentBalance: 320.0,
    creditLimit: 1000.0,
    notes: 'حساب علاج شهري للوالد (أدوية مزمنة)',
    createdAt: '2026-09-01',
  },
  {
    id: 'ent-7',
    name: 'د. سامي عمرو (عيادة الأطفال)',
    type: 'customer',
    phone: '0597114422',
    address: 'مجمع الأطباء التخصصي',
    currentBalance: 650.0,
    creditLimit: 2500.0,
    notes: 'مستلزمات طبية ولقاحات للعيادة',
    createdAt: '2026-08-28',
  },
];

export const initialMedicines: Medicine[] = [
  {
    id: 'med-1',
    barcode: '625100100201',
    tradeName: 'أوجمنتين 1 غرام (Augmentin 1g)',
    genericName: 'Amoxicillin + Clavulanic acid',
    category: 'مضاد حيوي',
    unit: 'علبة (14 قرص)',
    stockQuantity: 42,
    minQuantity: 10,
    purchasePrice: 28.0,
    sellPrice: 38.0,
    batchNumber: 'AUG-2026-08',
    expiryDate: '2027-11-30',
    manufacturer: 'GSK',
  },
  {
    id: 'med-2',
    barcode: '625100100202',
    tradeName: 'بانادول اكسترا (Panadol Extra)',
    genericName: 'Paracetamol + Caffeine',
    category: 'مسكنات وخافض حرارة',
    unit: 'علبة (24 قرص)',
    stockQuantity: 85,
    minQuantity: 20,
    purchasePrice: 9.5,
    sellPrice: 14.0,
    batchNumber: 'PAN-9941',
    expiryDate: '2028-04-15',
    manufacturer: 'Haleon',
  },
  {
    id: 'med-3',
    barcode: '625100100203',
    tradeName: 'بروفين 400 ملغ (Brufen 400mg)',
    genericName: 'Ibuprofen',
    category: 'مضاد التهاب ومسكن',
    unit: 'علبة (30 قرص)',
    stockQuantity: 18,
    minQuantity: 15,
    purchasePrice: 12.0,
    sellPrice: 18.0,
    batchNumber: 'BRF-2024-C',
    expiryDate: '2026-11-20',
    manufacturer: 'Abbott',
  },
  {
    id: 'med-4',
    barcode: '625100100204',
    tradeName: 'أوميبرازول 20 ملغ (Omeprazole)',
    genericName: 'Omeprazole',
    category: 'أدوية المعدة والحموضة',
    unit: 'علبة (28 كبسولة)',
    stockQuantity: 34,
    minQuantity: 8,
    purchasePrice: 15.0,
    sellPrice: 24.0,
    batchNumber: 'OME-552',
    expiryDate: '2027-08-31',
    manufacturer: 'دار الشفاء',
  },
  {
    id: 'med-5',
    barcode: '625100100205',
    tradeName: 'كونكور 5 ملغ (Concor 5mg)',
    genericName: 'Bisoprolol Fumarate',
    category: 'أمراض القلب والضغط',
    unit: 'علبة (30 قرص)',
    stockQuantity: 29,
    minQuantity: 10,
    purchasePrice: 22.0,
    sellPrice: 31.0,
    batchNumber: 'CNC-881',
    expiryDate: '2027-06-15',
    manufacturer: 'Merck',
  },
  {
    id: 'med-6',
    barcode: '625100100206',
    tradeName: 'فنتولين بخاخ (Ventolin Inhaler)',
    genericName: 'Salbutamol',
    category: 'الجهاز التنفسي والربو',
    unit: 'عبوة بخاخ',
    stockQuantity: 6,
    minQuantity: 12,
    purchasePrice: 18.0,
    sellPrice: 26.0,
    batchNumber: 'VEN-302',
    expiryDate: '2027-03-10',
    manufacturer: 'GSK',
  },
  {
    id: 'med-7',
    barcode: '625100100207',
    tradeName: 'فيتامين د3 (Vitamin D3 50,000 IU)',
    genericName: 'Cholecalciferol',
    category: 'فيتامينات ومكملات',
    unit: 'علبة (12 كبسولة)',
    stockQuantity: 50,
    minQuantity: 15,
    purchasePrice: 25.0,
    sellPrice: 38.0,
    batchNumber: 'VTD-104',
    expiryDate: '2028-01-20',
    manufacturer: 'بيرزيت',
  },
  {
    id: 'med-8',
    barcode: '625100100208',
    tradeName: 'كتافلام 50 ملغ (Cataflam 50mg)',
    genericName: 'Diclofenac Potassium',
    category: 'مسكن ومضاد التهاب',
    unit: 'علبة (20 قرص)',
    stockQuantity: 4,
    minQuantity: 10,
    purchasePrice: 16.0,
    sellPrice: 23.5,
    batchNumber: 'CAT-922',
    expiryDate: '2026-12-15',
    manufacturer: 'Novartis',
  },
  {
    id: 'med-9',
    barcode: '625100100209',
    tradeName: 'سيتريزين 10 ملغ (Cetirizine)',
    genericName: 'Cetirizine Dihydrochloride',
    category: 'حساسية ومضاد هيستامين',
    unit: 'علبة (20 قرص)',
    stockQuantity: 38,
    minQuantity: 10,
    purchasePrice: 8.0,
    sellPrice: 13.0,
    batchNumber: 'CET-401',
    expiryDate: '2027-09-10',
    manufacturer: 'دار الشفاء',
  },
  {
    id: 'med-10',
    barcode: '625100100210',
    tradeName: 'أتورفاستاتين 20 ملغ (Atorvastatin)',
    genericName: 'Atorvastatin Calcium',
    category: 'أدوية الكوليسترول والدهون',
    unit: 'علبة (30 قرص)',
    stockQuantity: 22,
    minQuantity: 8,
    purchasePrice: 26.0,
    sellPrice: 39.0,
    batchNumber: 'ATR-612',
    expiryDate: '2027-04-20',
    manufacturer: 'بيرزيت',
  },
];

export const initialTransactions: FinancialTransaction[] = [
  {
    id: 'tx-1',
    entityId: 'ent-1',
    entityName: 'صيدلية الأمل المركزية',
    date: '2026-09-15 10:30',
    amount: 1450.0,
    type: 'invoice',
    direction: 'debit',
    balanceAfter: 1450.0,
    referenceNumber: 'INV-10021',
    note: 'تبادل أدوية ونواقص لصالح صيدلية الأمل',
    recordedBy: 'م. مالك حريبات',
  },
  {
    id: 'tx-2',
    entityId: 'ent-2',
    entityName: 'صيدلية الشفاء الحديثة',
    date: '2026-09-20 14:15',
    amount: 820.0,
    type: 'invoice',
    direction: 'debit',
    balanceAfter: 820.0,
    referenceNumber: 'INV-10045',
    note: 'طلبية عاجلة - مسكنات ومضادات حيوية',
    recordedBy: 'م. مالك حريبات',
  },
  {
    id: 'tx-3',
    entityId: 'ent-3',
    entityName: 'شركة بيرزيت للصناعات الدوائية',
    date: '2026-09-10 11:00',
    amount: 6300.0,
    type: 'purchase',
    direction: 'credit',
    balanceAfter: -6300.0,
    referenceNumber: 'BILL-8890',
    note: 'فاتورة توريد طلبيات الشهر للأدوية العامة',
    recordedBy: 'د. سارة - محاسب',
  },
  {
    id: 'tx-4',
    entityId: 'ent-3',
    entityName: 'شركة بيرزيت للصناعات الدوائية',
    date: '2026-09-25 16:30',
    amount: 2000.0,
    type: 'payment_out',
    direction: 'debit',
    balanceAfter: -4300.0,
    referenceNumber: 'PAY-3011',
    note: 'سند صرف - دفعة نقدية تحت الحساب',
    recordedBy: 'م. مالك حريبات',
  },
  {
    id: 'tx-5',
    entityId: 'ent-4',
    entityName: 'مستودع أدوية القدس المركزي',
    date: '2026-09-18 12:00',
    amount: 2150.0,
    type: 'purchase',
    direction: 'credit',
    balanceAfter: -2150.0,
    referenceNumber: 'BILL-4412',
    note: 'توريد حليب أطفال ومستلزمات طبية',
    recordedBy: 'د. سارة - محاسب',
  },
  {
    id: 'tx-6',
    entityId: 'ent-6',
    entityName: 'أحمد محمود العواودة (زبون دائم)',
    date: '2026-10-01 18:40',
    amount: 320.0,
    type: 'invoice',
    direction: 'debit',
    balanceAfter: 320.0,
    referenceNumber: 'INV-10088',
    note: 'صرف وصفة علاج الضغط والسكري الشهرية على الحساب',
    recordedBy: 'د. سارة - صيدلانية',
  },
];

export const initialSales: SaleInvoice[] = [
  {
    id: 'sale-1',
    invoiceNumber: 'INV-10088',
    date: '2026-10-01 18:40',
    entityId: 'ent-6',
    entityName: 'أحمد محمود العواودة (زبون دائم)',
    items: [
      {
        medicineId: 'med-5',
        medicineName: 'كونكور 5 ملغ (Concor 5mg)',
        quantity: 2,
        unitPrice: 31.0,
        subtotal: 62.0,
      },
      {
        medicineId: 'med-10',
        medicineName: 'أتورفاستاتين 20 ملغ (Atorvastatin)',
        quantity: 2,
        unitPrice: 39.0,
        subtotal: 78.0,
      },
      {
        medicineId: 'med-4',
        medicineName: 'أوميبرازول 20 ملغ (Omeprazole)',
        quantity: 2,
        unitPrice: 24.0,
        subtotal: 48.0,
      },
      {
        medicineId: 'med-7',
        medicineName: 'فيتامين د3 (Vitamin D3 50,000 IU)',
        quantity: 3,
        unitPrice: 38.0,
        subtotal: 114.0,
      },
      {
        medicineId: 'med-2',
        medicineName: 'بانادول اكسترا (Panadol Extra)',
        quantity: 1,
        unitPrice: 14.0,
        subtotal: 14.0,
      },
    ],
    totalAmount: 316.0,
    discount: 0,
    tax: 0,
    finalAmount: 316.0,
    paidAmount: 0,
    remainingAmount: 316.0,
    paymentMethod: 'credit',
    paymentStatus: 'unpaid',
    cashierName: 'د. سارة - صيدلانية',
    notes: 'تسجيل على حساب العميل الشهري',
  },
  {
    id: 'sale-2',
    invoiceNumber: 'INV-10089',
    date: '2026-10-05 10:15',
    entityName: 'زبون نقدي',
    items: [
      {
        medicineId: 'med-1',
        medicineName: 'أوجمنتين 1 غرام (Augmentin 1g)',
        quantity: 1,
        unitPrice: 38.0,
        subtotal: 38.0,
      },
      {
        medicineId: 'med-2',
        medicineName: 'بانادول اكسترا (Panadol Extra)',
        quantity: 2,
        unitPrice: 14.0,
        subtotal: 28.0,
      },
    ],
    totalAmount: 66.0,
    discount: 0,
    tax: 0,
    finalAmount: 66.0,
    paidAmount: 66.0,
    remainingAmount: 0,
    paymentMethod: 'cash',
    paymentStatus: 'paid',
    cashierName: 'م. مالك حريبات',
  },
];

export const initialExpenses: Expense[] = [
  {
    id: 'exp-1',
    title: 'إيجار الصيدلية الشهري - تشرين أول',
    category: 'rent',
    amount: 1500.0,
    date: '2026-10-01',
    notes: 'تم الدفع لصاحب العقار نقداً',
    recordedBy: 'م. مالك حريبات',
  },
  {
    id: 'exp-2',
    title: 'فاتورة الكهرباء والتكييف',
    category: 'electricity',
    amount: 320.0,
    date: '2026-10-03',
    notes: 'تشغيل ثلاجات حفظ الأدوية والتكييف المركزي',
    recordedBy: 'د. سارة - محاسب',
  },
  {
    id: 'exp-3',
    title: 'مستلزمات نظافة وأكياس أدوية مطبوعة',
    category: 'supplies',
    amount: 180.0,
    date: '2026-10-04',
    notes: 'أكياس ورقية صديقة للبيئة بشعار الصيدلية',
    recordedBy: 'م. مالك حريبات',
  },
];
